import crafttweaker.item.IIngredient;
import mods.recipestages.Recipes;

var stagedItems as IIngredient[][string] = {
    [ENG_1]:[
        <techguns:explosive_charge>,
        <techguns:itemshared>,
        <techguns:itemshared:1>,
        <techguns:itemshared:2>,
        <techguns:itemshared:10>,
        <techguns:itemshared:12>,
        <techguns:itemshared:14>,
        <techguns:itemshared:33>,
        <techguns:itemshared:34>,
        <techguns:itemshared:37>,
        <techguns:itemshared:38>,
        <techguns:itemshared:42>,
        <techguns:itemshared:89>,
        <techguns:itemshared:90>,
        <techguns:itemshared:91>,
        <techguns:itemshared:93>,
        <techguns:itemshared:132>,
        <techguns:gasmask>,
        <techguns:glider>,
        <techguns:combatknife>,
        <techguns:crowbar>,
        <techguns:t1_combat_helmet>,
        <techguns:t1_combat_chestplate>,
        <techguns:t1_combat_leggings>,
        <techguns:t1_combat_boots>,
        <techguns:t1_scout_helmet>,
        <techguns:t1_scout_chestplate>,
        <techguns:t1_scout_leggings>,
        <techguns:t1_scout_boots>,
        <techguns:t1_miner_helmet>,
        <techguns:t1_miner_chestplate>,
        <techguns:t1_miner_leggings>,
        <techguns:t1_miner_boots>,
        <techguns:hazmat_helmet>,
        <techguns:hazmat_chestplate>,
        <techguns:hazmat_leggings>,
        <techguns:hazmat_boots>,
        <techguns:riot_shield>,
        <techguns:t2_beret>,
        <techguns:handcannon>.withTag({ammo: 1 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:sawedoff>.withTag({ammo: 2 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:revolver>.withTag({ammo: 6 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:thompson>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:ak47>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:boltaction>.withTag({ammo: 6 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:itemshared:39>,
        <techguns:pistol>.withTag({ammo: 18 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:combatshotgun>.withTag({ammo: 8 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:mac10>.withTag({ammo: 32 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:stielgranate>
    ],
    [ENG_2]:[
        <techguns:basicmachine:3>,
        <techguns:explosive_charge:1>,
        <techguns:itemshared:7>,
        <techguns:itemshared:16>,
        <techguns:itemshared:24>,
        <techguns:itemshared:28>,
        <techguns:itemshared:35>,
        <techguns:itemshared:43>,
        <techguns:jumppack>,
        <techguns:scubatanks>,
        <techguns:nightvisiongoggles>,
        <techguns:jetpack>,
        <techguns:tacticalmask>,
        <techguns:steam_helmet>.withTag({power: 0}),
        <techguns:steam_chestplate>.withTag({power: 0}),
        <techguns:steam_leggings>.withTag({power: 0}),
        <techguns:steam_boots>.withTag({power: 0}),
        <techguns:t2_combat_helmet>,
        <techguns:t2_combat_chestplate>,
        <techguns:t2_combat_leggings>,
        <techguns:t2_combat_boots>,
        <techguns:t2_commando_helmet>,
        <techguns:t2_commando_chestplate>,
        <techguns:t2_commando_leggings>,
        <techguns:t2_commando_boots>,
        <techguns:t2_riot_helmet>,
        <techguns:t2_riot_chestplate>,
        <techguns:t2_riot_leggings>,
        <techguns:t2_riot_boots>,
        <techguns:ballistic_shield>,
        <techguns:advanced_shield>,
        <techguns:goldenrevolver>.withTag({ammo: 6 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:m4>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:m4_infiltrator>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:flamethrower>.withTag({ammo: 100 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:rocketlauncher>.withTag({ammo: 1 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:aug>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:lmg>.withTag({ammo: 100 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:grenadelauncher>.withTag({ammo: 6 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:vector>.withTag({ammo: 25 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:scar>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:fraggrenade>,
        <techguns:powerhammer>.withTag({ammo: 300 as short, ammovariant: "default", miningHead: 0, camo: 0 as byte}),
        <techguns:chainsaw>.withTag({ammo: 300 as short, ammovariant: "default", miningHead: 0, camo: 0 as byte}),
        <techguns:miningdrill>.withTag({ammo: 300 as short, ammovariant: "default", miningHead: 0, camo: 0 as byte})
    ],
    [ENG_3]:[
        <techguns:itemshared:18>,
        <techguns:itemshared:20>,
        <techguns:itemshared:22>,
        <techguns:itemshared:30>,
        <techguns:itemshared:32>,
        <techguns:itemshared:26>,
        <techguns:itemshared:36>,
        <techguns:itemshared:41>,
        <techguns:itemshared:40>,
        <techguns:itemshared:44>,
        <techguns:itemshared:128>,
        <techguns:itemshared:129>,
        <techguns:itemshared:130>,
        <techguns:antigravpack>,
        <techguns:t3_combat_helmet>,
        <techguns:t3_combat_chestplate>,
        <techguns:t3_combat_leggings>,
        <techguns:t3_combat_boots>,<techguns:t3_power_helmet>.withTag({power: 0}),
        <techguns:t3_power_chestplate>.withTag({power: 0}),
        <techguns:t3_power_leggings>.withTag({power: 0}),
        <techguns:t3_power_boots>.withTag({power: 0}),
        <techguns:t3_miner_helmet>.withTag({power: 0}),
        <techguns:t3_miner_chestplate>.withTag({power: 0}),
        <techguns:t3_miner_leggings>.withTag({power: 0}),
        <techguns:t3_miner_boots>.withTag({power: 0}),
        <techguns:t3_exo_helmet>.withTag({power: 0}),
        <techguns:t3_exo_chestplate>.withTag({power: 0}),
        <techguns:t3_exo_leggings>.withTag({power: 0}),
        <techguns:t3_exo_boots>.withTag({power: 0}),
        <techguns:t4_praetor_helmet>.withTag({power: 0}),
        <techguns:t4_praetor_chestplate>.withTag({power: 0}),
        <techguns:t4_praetor_leggings>.withTag({power: 0}),
        <techguns:t4_praetor_boots>.withTag({power: 0}),
        <techguns:grimreaper>.withTag({ammo: 4 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:netherblaster>.withTag({ammo: 10 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:biogun>.withTag({ammo: 30 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:teslagun>.withTag({ammo: 25 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:minigun>.withTag({ammo: 200 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:as50>.withTag({ammo: 10 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:lasergun>.withTag({ammo: 45 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:blasterrifle>.withTag({ammo: 50 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:scatterbeamrifle>.withTag({ammo: 40 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:sonicshotgun>.withTag({ammo: 8 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:pdw>.withTag({ammo: 40 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:pulserifle>.withTag({ammo: 12 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:mibgun>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:alienblaster>.withTag({ammo: 10 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:nucleardeathray>.withTag({ammo: 40 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:gaussrifle>.withTag({ammo: 8 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:guidedmissilelauncher>.withTag({ammo: 1 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:tfg>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte}),
        <techguns:laserpistol>.withTag({ammo: 20 as short, ammovariant: "default", camo: 0 as byte})
    ],
    [TCH_1]:[
        <techguns:simplemachine:8>,
        <techguns:simplemachine:9>,
        <techguns:simplemachine:10>,
        <techguns:itemshared:57>,
        <techguns:itemshared:60>,
        <techguns:itemshared:62>,
        <techguns:itemshared:63>,
        <techguns:itemshared:65>,
        <techguns:itemshared:68>,
        <techguns:itemshared:70>,
        <techguns:itemshared:72>,
        <techguns:itemshared:99>,
        <techguns:itemshared:125>,
        <techguns:itemshared:133>.withTag({display: {}}),
        <techguns:itemshared:147>,
        <techguns:itemshared:148>,
        <techguns:itemshared:149>
    ],
    [TCH_2]:[
        <techguns:simplemachine2:9>,
        <techguns:itemshared:58>,
        <techguns:itemshared:66>,
        <techguns:itemshared:100>,
        <techguns:itemshared:101>,
        <techguns:itemshared:121>,
        <techguns:itemshared:123>,
        <techguns:itemshared:119>,
        <techguns:itemshared:150>,
        <techguns:itemshared:151>,
        <techguns:itemshared:152>
    ],
    [TCH_3]:[
        <techguns:itemshared:59>,
        <techguns:itemshared:102>,
        <techguns:itemshared:122>,
        <techguns:itemshared:124>,
        <techguns:itemshared:131>,
        <techguns:itemshared:120>,
        <techguns:itemshared:153>,
        <techguns:itemshared:154>,
        <techguns:itemshared:155>
    ],
    [MNF_1]:[
        <techguns:basicmachine>,
        <techguns:basicmachine:1>,
        <techguns:simplemachine:11>,
        <techguns:simplemachine2:8>
    ],
    [MNF_2]:[
        <techguns:itemshared:94>
    ],
    [MNF_3]:[
        <techguns:multiblockmachine>,
        <techguns:multiblockmachine:1>,
        <techguns:multiblockmachine:2>,
        <techguns:oredrill>,
        <techguns:oredrill:1>,
        <techguns:oredrill:2>,
        <techguns:oredrill:3>,
        <techguns:oredrill:4>,
        <techguns:itemshared:104>,
        <techguns:itemshared:118>,
        <techguns:itemshared:134>,
        <techguns:itemshared:135>,
        <techguns:itemshared:136>,
        <techguns:itemshared:137>,
        <techguns:itemshared:138>,
        <techguns:itemshared:139>,
        <techguns:itemshared:140>,
        <techguns:itemshared:141>,
        <techguns:itemshared:142>
    ],
    [CHM_1]:[
        <techguns:basicmachine:2>,
        <techguns:multiblockmachine:5>,
        <techguns:multiblockmachine:4>,
        <techguns:multiblockmachine:3>
    ],
};

for stageName, items in stagedItems {
  for item in items {
    Recipes.setRecipeStage(stageName, item);
  }
}

var toRemove = [
] as IIngredient[];

for item in toRemove {
  recipes.remove(item);
}
